# Generated by Django 5.1.6 on 2025-07-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_coursecontent_coursemember_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('content', models.TextField(verbose_name='Konten')),
                ('show_at', models.DateTimeField(verbose_name='Tampilkan pada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='lms_core.course', verbose_name='Mata Kuliah')),
            ],
            options={
                'verbose_name': 'Pengumuman Mata Kuliah',
                'verbose_name_plural': 'Pengumuman Mata Kuliah',
                'ordering': ['-show_at'],
            },
        ),
    ]
