# Generated by Django 5.1.6 on 2025-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0007_contentbookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentbookmark',
            options={},
        ),
        migrations.AddField(
            model_name='contentbookmark',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
